glide.lock, yaml_benchmark_test.go
If that particular benchmark was testing something in particular we
shuold bring it back, but not rely on another external package to test
something related to the config.
=> Remove reference to zap

provider_group.go, provider_group_test.go
Group provider iterates over all underlying providers until it finds a value, which works for structs, because we know key in advance, but fails for maps, where keys are dynamic.
We are going to reuse the mergeMaps function to merge values from all providers.
=> Fix group provider for maps

config.go, config_test.go
The loader logic is extremely convoluted and not actually concurrent safe, which makes this test to fail sometimes.
=> Skip parallel load test

static_provider_test.go, value.go
WithDefaultValue replaces only a default value, which makes it to work only with scalar types, but more complex types will [fail](https://github.com/uber-go/config/issues/16).
We can update the provider saved in value to be a grouped provider of the original provider and a static provider based on the provided value.
=> Make WithDefault to provide a deep copy of the provided default value

config.go
When using `config.TestConfig` in our application, we were not reading the configuration files from the application root's `config/` directory. This change makes it so that we read from the root if the APP_ROOT variable is set, or the current working directory otherwise.
=> Use APP_ROOT to resolve configuration path(s)

decoder.go, value.go, yaml_test.go
`Populate` is using `encoding.TextUnmarshaller` interface only on scalar types, 
functions and channels, but any type can implement it, e.g. [zap.AtomicLevel](https://github.com/uber-go/zap/blob/master/level.go#L109)
We are using `Value.String()` to construct the byte array. In case of scalar types
received from a provider, text does not need extra formatting. `TextUnmarshaller`
implementation should be aware of the source of the values for complex types.
For example in `TestUnmarshalTextOnComplexStruct` the actual contents of byte 
array are `map[year:1994 title:Free Willy]`
=> Check implementation of TextUnmarshaller on all types

CHANGELOG.md, cache_provider_test.go, command_line_provider.go, config_test.go, decoder.go, nop_provider.go, provider_group.go, static_provider_test.go, value.go, value_provider.go, yaml.go, yaml_test.go
We have several bugs related to collections:
1. [Populate doesn't fail on malformed data](https://github.com/uber-go/config/issues/21)
1. [Command line is implemented via maps, so slices aliases can't be used for unmarshaling data](https://github.com/uber-go/config/issues/29).
1. Populate for slices iterates only until a first nil element, even if a collection is larger.
1. ValueType doesn't differentiate between slices and arrays - it is removed, one can simply rely on `reflect.Kind(v.Value())`
I've merged all the above bugs into 1 PR, because it is harder to fix these issues atomically(it would require more code changes)
@akshayjshah and @abhinav I understand, that you are not familiar with the code base, so it is mostly FYI.
=> Check underlying collection types

static_provider_test.go, value.go, yaml_test.go
=> Try methods should return false for missing values

CHANGELOG.md, decoder.go, yaml_test.go
Sometimes configuration structs can contain public fields that are channels/functions that don't implement TextUnmarshaller/UnmarshalYAML interfaces. They are are supposed to be field manually/by another function and errors break this flow. We should silently skip them instead, an example is [json.Unmarshal](https://golang.org/pkg/encoding/json/#Unmarshal)
=> Skip inappropriate types instead of reporting errors on them

Makefile
Most of the tests already run in parallel, but I also don't want tests to have any saved records in global variables. Running them twice will make sure that everything is cleaned up correctly.
=> Run tests twice

CHANGELOG.md, value.go
There is no particular reason for a `Timestamp` to be a public field, but keeping everything else private. With this change all access to `Value`'s internal fields will be done via methods.
=> Make Value.Timestamp private

CHANGELOG.md, decoder.go, glide.lock, glide.yaml, static_provider.go, yaml.go
Most of the projects are using semantic version paths(e.g. yarpc, dosa, tally),
so it is better to be in sync with them.
=> Use semantic version paths for yaml and validator packages

CHANGELOG.md, config.go, config_test.go
Right now there is no easy way of skipping command line provider which can conflict with another command line libraries. Instead of requiring user to set up all the flags in the `pflag.CommandLine` variable we'll read `commandline` value from previously loaded providers(yaml files).
=> Let user to skip loading command line provider via  parameter.

CHANGELOG.md, config_test.go, static_provider.go, static_provider_test.go, yaml.go, yaml_test.go
These constructors are not used by anyone internally and it is much easier either to load a provider from file or use a static provider for testing.
=> Make YAML constructors from io.ReadCloser internal

CHANGELOG.md, config_test.go, provider_group.go, static_provider_test.go, value.go
There is no need to have an extra semantic of checking if a value is a default one.
User can make a new value with extra defaults via `Value.WithDefault`, but checking
for a default is very cumbersome: how can we differentiate a zero value and
a default value that is a zero value for a type.
=> Remove IsDefault method

CHANGELOG.md, config.go, config_test.go, static_provider.go, static_provider_test.go, yaml.go, yaml_test.go
We don't really need Load* functions, because users can use constructors directly to load files.
File name to load config, that is based on the environment variable is also too company specific.
=> Remove Load* function

CHANGELOG.md, decoder.go, static_provider_test.go, yaml_test.go
We invoke `TextUnmarshaler.UnmarshalText` even if a value is missing from a config, which will lead to errors like https://github.com/uber-go/config/issues/55. We should keep a zero initialized value instead of unmarshalling an empty string.
=> Fix unmarshal text on missing value.

CHANGELOG.md, static_provider_test.go, value.go, version.go
We can't populate a value if there no value.
`reflect.Indirect` of a nil pointer returns an invalid `reflect.Value` and panics in the decoder.
=> Fixed populate panic for a nil pointer

CHANGELOG.md, expand.go, expand_test.go, glide.lock, glide.yaml, static_provider.go, static_provider_test.go, testdata/base.yaml, yaml.go, yaml_test.go
Currently NewYAMLProviderFromFiles() and NewYAMLProviderWithExpand() do not produce the same result when given the same input, even when the input contains only simple values with no expansion variables.  The expansion feature has a side-effect which converts all fields into strings.
This can be demonstrated with:
package main
import "fmt"
import "os"
import "go.uber.org/config"
func main() {
if len(os.Args) != 3 {
fmt.Fprintf(os.Stderr, "Usage: %s config.yaml field\n",
os.Args[0])
os.Exit(1)
}
filename := os.Args[1]
field := os.Args[2]
cfg, _ := config.NewYAMLProviderFromFiles(filename)
val := cfg.Get(field)
fmt.Printf("%s: %v (%T)\n", field, val.Value(), val.Value())
cfg, _ = config.NewYAMLProviderWithExpand(os.LookupEnv, filename)
val = cfg.Get(field)
fmt.Printf("%s: %v (%T)\n", field, …
=> Perform variable expansion using text.Transformer

config_test.go, expand_test.go, static_provider.go, static_provider_test.go, yaml.go, yaml_test.go
Export the already-existing constructor functions that take `io.Reader`. This
helps build `Provider`s from sources other than files.
=> Export Provider constructors taking io.Reader

config_ext_test.go
Before making any significant changes to the config logic, add a suite
of unit tests that exercise the externally-visible behavior of the
current implementation. A number of these tests currently fail, so
they're skipped and marked with todos.
This includes tests that replicate the following issues:
- https://github.com/uber-go/config/issues/72
- https://github.com/uber-go/config/issues/59
- https://github.com/uber-go/config/issues/76
- https://github.com/uber-go/config/issues/75
=> Add a suite of external integration tests

value_ext_test.go
*WIP, but please take a look and discuss.*
This is...unfortunate. Unless users are very careful, the behavior of
`NewValue` is completely irrational. These tests aren't exhaustive, but
the gist is this:
* `NewValue` takes a provider, a key, a value (as `interface{}`), and a
bool indicating whether the value was found or not. There's currently no
validation checking that `value` and `found` match the contents of the
provider at the specified key.
* `HasValue` returns the user-supplied bool, ignoring the contents of
the provider.
* `String` and `Value` return the user-supplied value, ignoring the
contents of the provider.
* `Populate`, `Get`, and `WithDefault` use the provider, ignoring the
user-supplied value and bool.
This leads to a lot of potentially counter-intuitive behavior. Since …
=> Add integration tests for NewValue

Makefile
Clean up a few more odds and ends in the Makefile, including a
mistakenly commented-out line.
=> Small Makefile cleanups

expand_test.go
The tests for environment variable expansion are simple and fast -
there's no need to sprinkle calls to `t.Parallel` all over, since
starting a goroutine is nearly as expensive as just running the test.
=> Remove parallelization from expansion tests

internal/merge/merge.go, internal/merge/merge_test.go, internal/merge/testdata/base.yaml, internal/merge/testdata/expect.yaml, internal/merge/testdata/production.yaml
Since we're only planning to use this package during process startup,
there's no need to micro-optimize our YAML merging. Given that, we can
implement our deep-merging logic in a small, standalone package that
doesn't require any explicit reflection. That package takes a more naive
approach than our current logic: it unmarshals all YAML sources into
`interface{}`, merges the resulting Go values, and re-serializes the
merged `interface{}` to YAML.
=> Add a small package to deep-merge YAML

CHANGELOG.md
The changelog wasn't very well-groomed, and some of the entries were actually incorrect. Reword and switch to the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format.
=> Switch to Keep a Changelog format

CHANGELOG.md
Update changelog to v1.2.0. The version constant is already at the
correct value.
=> Prepare for v1.2.0

CHANGELOG.md, config.go, config_ext_test.go, internal/merge/merge.go, internal/merge/merge_test.go, option.go, option_test.go
We're currently handling empty (or comment-only) and null YAML sources
incorrectly. This diff fixes both by simplifying the configuration
provider even further.
These sources are problematic for two reasons. First, we're not
special-casing `io.EOF` errors when we use `yaml.Decoder`. More
insidiously, when we unmarshal sources, we're not distinguishing between
nil values caused by empty (or comment-only) sources and explicit
top-level nulls. The latter is particularly problematic because an
explicit null should be higher-priority than all defaults provided via
`WithDefault`, even if that null is itself overriden by another YAML
source. (For example, if `base.yaml` is just `~` and `production.yaml`
is `foo: bar`, the explicit top-level null in `base.yaml` should trump
any data supplied by …
=> Handle empty and null sources correctly

.codecov.yml
Our internal OSS process suggests a bar of 90% coverage. We should aim
for more, but let's not block PRs until we drop below that bar.
=> Lower coverage target to 90%

CHANGELOG.md, config.go, config_ext_test.go, constructors.go
We were encountering a bug where `NewProviderGroup` was interpreting
empty files correctly despite the previous fix. Specifically, the
following works with `NewYAML`,
#
p := NewYAML(File("foo.yaml"), File("empty.yaml")))
fmt.Println(p.Get("foo.bar").Value())
// Output: 42
But the following does not,
p1 := NewYAML(File("foo.yaml"))
p2 := NewYAML(File("empty.yaml"))
p  := NewProviderGroup(p1, p2)
fmt.Println(p.Get("foo.bar").Value())
// Output: nil
It doesn't work because `NewProviderGroup` works by calling `Get(Root)`
on the providers and building a new `Provider` with the merged contents.
`p2` doesn't know the difference between empty file and `nil` so it
returns `nil` for its contents, which the merging logic interprets as
unsetting everything at that level.
Unfortunately, switching this …
=> NewProviderGroup: Handle empty sources correctly

CHANGELOG.md, config.go, config_ext_test.go, internal/merge/merge.go
YAML mappings can be keyed by any kind of node so long as it is unique.
That means a mapping key can be an integer, a boolean, or a number of
other types besides a string.
`Get` retrieves a value on a period-separated path and previously
interpreted each segment as a string. This change unmarshals each path
segment to produce comparable map keys, even if it's a bit strange when
"no: car" content produces a value with `provider.Get("false")`.
Resolves #104
=> YAML: support non-string scalar keys

CHANGELOG.md, config.go, config_ext_test.go, expand.go, option.go, version.go
To make `WithDefault` handle explicit nils correctly, we need to work
directly with the original YAML sources. When re-merging these sources
with the new default source, we neglected to re-expand environment
variables. This effectively made any Values created by `WithDefault`
behave as though environment variable expansion were disabled.
In this commit, we fix this bug by re-expanding env vars in
`WithDefault`. This isn't ideal, since it requires reaching out into the
environment again, but it's very simple. The more-correct alternative
requires parsing all environment variables out of every YAML source and
looking them up during provider construction, then using that lookup
table in subsequent calls to `WithDefault`. Since `WithDefault` is
deprecated and the environment doesn't usually …
=> Re-expand env vars in WithDefault

CHANGELOG.md
This fixes the changelog to match the keepachangelog format we claim to
conform to.
Specifically, it adds links to the list of changes made between releases
and uses just the version numbers for the headers, without the `v`
prefixes, which need to be present only in the Git tags.
=> CHANGELOG: Confirm to keepachangelog.com

.github/workflows/go.yml, go.mod, tools_test.go
We only support the most recent two Go minor versions.
=> CI: Run on Go 1.17/1.18

.github/workflows/go.yml, config.go, doc.go, go.mod, go.sum, internal/merge/merge.go, option.go
This makes the CI run on Go 1.19, and fix the formatting issues per the new go doc format in 1.19.
=> Use Go 1.19 and run gofmt
